[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5d844648385063a2f0fd617cb0c5a5db50db26b"
os = "freebsd"

    [[libcxxwrap_julia.download]]
    sha256 = "09581f5c73a49be6b192b62380340561510256fc2c7f111c601a120067f13fd6"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+1/libcxxwrap_julia.v0.7.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26e1f4739acafceedfb5fa545671ba787fd40010"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "5234d469d9d2505fc1d673553ec2fecd218ea488c83906e91182ea3f527399f9"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+1/libcxxwrap_julia.v0.7.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9530965e6a2fbdf8c857a5cd4729be80f215dc69"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "b0103dcd5d38833874d8f79355ea7ded4c7c987adc275aa51c76e744b232f990"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+1/libcxxwrap_julia.v0.7.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d54e82277daeea66dbc6729a14f8fae78fed582"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "17f694d2194851957172c3b1ae873af8e7cfad610d99f07e1f6c6c9b839b688d"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+1/libcxxwrap_julia.v0.7.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "181061893da01b1ef9ebac774144fd9d32d19aee"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "78ff31de6f99ee8cc5ba500cd79c13353d5de31e8138ff2bc44b42be39d708fe"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+1/libcxxwrap_julia.v0.7.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d54a2909808f0f05123ef98f8eef4fcde1073e52"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "7a8ee2b7f81a299c884cdfe031b1d50d1479f26f4a3f7acc6c079435f55ae886"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+1/libcxxwrap_julia.v0.7.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3dbab8aa1f22d249cca1d7af5bc7d826e641960f"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "ae609b5b0e4a199e62bc03522e57580152ea0005909ce702458978bf9392f6ea"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+1/libcxxwrap_julia.v0.7.1.i686-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1efcae9ec164b1cdc9449d6da540bc51942b880a"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "35c7f1a2987fbf4118458d0b3dfd30760fe1ae2cc74f7544632eff8f521a0d93"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+1/libcxxwrap_julia.v0.7.1.i686-w64-mingw32-cxx11.tar.gz"
