[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74f0e6a634f203f430a7fa9709d44de97eb94cf9"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "71f8a32f5e576307464d72cde8e097e0daa88667ed1e4132868801bf57f97e82"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.0+0/libcxxwrap_julia.v0.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "097c7b8225a4cde6810c9521f8764b85ee698a2f"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "eb8fe118694b3cc0c90d3999d2fddb8a0e90c25e949340549ff6aa34ae8ab103"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.0+0/libcxxwrap_julia.v0.8.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69fa9ffbf61c1bd0ac2e6d152358fb1d45a5f4f2"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "41f63e45ba73a94c7d67f1c58dd23fb8a1e5d54f26dcdc76a111fc8cb117dc76"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.0+0/libcxxwrap_julia.v0.8.0.i686-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39c90bbc296bee246430f125b09750c85c849343"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "3054fa1206826fbe4f01cf72760897800d7fab564c00bdff5df9a8db14893220"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.0+0/libcxxwrap_julia.v0.8.0.i686-w64-mingw32-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6017255205dc4fbf4d962903a855a0c631f092dc"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "5c3659ceb946fd4fc647b9a2af48dc6c95d2d5600649d752a1512e1bd7122d59"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.0+0/libcxxwrap_julia.v0.8.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd5dfb5dee87c41c238d98bd7ff2fdd4f307e824"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "cc0241496fccd45dff89bf95d4b83d451e8efe00b13b086c718ea925f00b29ad"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.0+0/libcxxwrap_julia.v0.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1445c8dd0b519014f23cbccc5ef1a36c393ad35d"
os = "freebsd"

    [[libcxxwrap_julia.download]]
    sha256 = "8bbbd52acb67a270a1c718aea8e4b8c0bf671192dce2714a5276cbbbdf740335"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.0+0/libcxxwrap_julia.v0.8.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dac68fb2ef8659814ad2c5a606b2a1aa22d451ff"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "35f62308fa2c84f4df66e54e4f1bc604eabf318e37a969a055c2f3dc71fc637d"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.0+0/libcxxwrap_julia.v0.8.0.x86_64-w64-mingw32-cxx11.tar.gz"
