[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b121b4df854fb29267fdafe1763263d9d5050d7"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "7c1144419ca87d55b8303372f180ae53b475b5c3724244252c122c1efe5497b6"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0f78f6d8a8cce4e0f756c6975e3ce4efaba1a6a"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "476f8f54eb8217ca3f733cdd4bd2dde1a3ee2491a92fd2ac9e972e543e41676d"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fa40b247f36c8f21d1e1f99dd3b1cd02285015e"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "897ce3463b7e1a26f3537fd625638dd44214d67eba17fcee065331ad9e14df27"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.aarch64-linux-musl-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aaf4d61e289bf8d58073a6daa84ff68d9facdf1a"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "f10d7bbbc5b1adafffd13af7aeee03e5f1dfa8d1d8fc76e9b0be26b13be55b52"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.aarch64-linux-musl-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0a87a5cded4a78d03ea3f45a12c2bd34c1c880d"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "3d59bab0e42112f11912b5a546b0b72181cff2b0a9cceaf1c8220fc9ba6f6e62"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3a9e22f0a54674963c2a9d50dcc076db26363e0"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "44063f1f6414be81bebed7de28f0336b0c73d5e79d0ce48a62b28e762b12b146"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dab685834c1397c5b62eab7cd474d8005f5ed550"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "38ef0bc466328d1b912374fc2ad50f7b0413b902e5605fa83e215025be115795"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5737a6576b470b225dd985b959c139dc54b96669"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "998aa6030553bd6dadcbb686b249b06b99926fa8ac2d76eb4faee32c0e49e790"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "201738d707071804bfdd1183789ee6fff2e23024"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "867b03966aa0a682461d2244a1b81eb952905458499c72c0fcf9896fc4887e46"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.i686-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab46879c53ff4702ef0a5ab9fd84d94157460686"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "678e3248c56aa263b797e43adeb74729cf0c792832e9f8955dd40635eaed3ee6"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.i686-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e41a7d0d4aa50eec653ff9086691bf1437eac278"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "296ffb32544c5fed7525f68d9c603b650aaedae30b0cf9bdd5067dd2b9547407"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.i686-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b5a3e25281ca79d63b7ca646747899fa4314292"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "44275d0bcd85f7b197b36c05c10367359403958cedc71e1a6d582305756f1068"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.i686-w64-mingw32-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06034aafba3ce84d10410037a9bc07ba6fa7946a"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "7c26ac6952469382809ddeb5e763d28a24caa6af816e37207b0059db9adc0682"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7976bad2b915bb63563443a15d099251c2c1bce2"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "086698a8354aaba24f5c6660702ba2cb07a517ce05632208ed048fef42f823c7"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "0eb6ffcbe0cde10007a2678013611da80643b728"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "9f41dd60fe2d6b923074e387c02e805742e5e786b547b6c8265b1616e1413801"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.x86_64-apple-darwin.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f7477447dd67d85c5c0781878e284f7f3ae4e87"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "d5e6b1fa02405a0de3de264dc076afac2b5d734167d8671093fbc2e0658d6390"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a6fdb6b1893826a3949ec0b4857a8277daa2eb9"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "c2842bed3736d379152d514143f16fa6d5fc518bf37b4c66f987941be93839eb"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f7f2827063a1f816749dc934465356ff35827ba"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "987754c8b1ae13145028cc3609e4756cb325d08ea558f5e79e69238deff2990b"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.x86_64-linux-musl-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad645cf7a90d3e3f2e99b70bf976e6d022691aae"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "a27f89aff3740b30c11f2c175337295a0124928af9414ea3cc32771239b1db17"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.x86_64-linux-musl-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "c603f77241c370738ece97f62b6b5bea613e0ef8"
os = "freebsd"

    [[libcxxwrap_julia.download]]
    sha256 = "c0d24df652cd6eb03db90e2f04aa885c6bd5c6eab37dcb5f25cc67082bd8c14f"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.x86_64-unknown-freebsd.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0994c54b555943d5441c5766042ff1bbe6e1873c"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "07bc47ba4b808acfdb84e7b30e6f23bf9f292acb6afb20490218080fbdf72e4a"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55b3eb5b24955f2171c0e24fe9c78d153305070d"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "fd09e7b818cb1b3a54e2d48401eecece8b5eb1263bf3dd3a681cb427439646e3"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.5+1/libcxxwrap_julia.v0.8.5.x86_64-w64-mingw32-cxx11.tar.gz"
