[[libcxxwrap_julia]]
arch = "aarch64"
git-tree-sha1 = "5b08c36bbf49fa172bd14a1feb517d172e00025a"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "3deca7c0bd6415f8cc3fc892056a2d418181dbc5a266c4f86f98819a45c09808"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.aarch64-apple-darwin.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e686e95b6f786672fa96afce5a2d5369b65c067"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "3428b80bcf6805a6a15e9485e6cedeb32e8c81db5f52fdec0d9722e02a3d3086"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.aarch64-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c61dba73e20efe55d88edad218dc8dc0241124a"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "0a673f8b83d22364cc7cba999d97c271fc7c4c5c95e0a362295f97bc541498f5"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.aarch64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8dbba6509559876d9bd6a0470ce0b3afcd6fa18"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "fd59a7e41e8eb0bb789f7ba45450feb88ffb1426b55989283036e55be779d552"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.aarch64-linux-musl-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4e5fb102f3ac1f81e95a8b5666b9a05156e4b00"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "2c473f02652eb9028a9c9d77a1c8db35bfac396aa546cf5eaa552eb49f2387d3"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.aarch64-linux-musl-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e140ac31401ad3fb6230105386f5025b1c841a49"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "2c16a52e6097393bd1bbd4faf0e954e7fce8dc5ca0c92ef174a0760416051b04"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33edbde9d5598717eef7db762c7fd394db35e1ad"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "1d56f21cc116a0dd2e4d48d904538775481177baefdc26a11e4ac1926bb78f63"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17f90de3effe43bbb635ac22cdffb2d2517a8ebc"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "3756fb1af46ccdcff813a7aba440a6699113503f3e22497c007b950118dd2f45"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffbdff08b3e90e1735edfa79435a3f79284bca0c"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "d2258633c1b7ebd5429caf0253a868b6608977fc98e2b163f62a4d8852ff273b"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3043ff5ca6391236b9dc5b2de6baf5358f90622b"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "5bb37bbdad224ee4de0a4592e5ebf5748dc212f526df48c9beae676e6cecfd4e"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04a4ca65b08b442e168cc14a47a5c0cce45f09d1"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "2f1bd7a43fceac0bf4d89c88a621777bd8ecc23e4c1becfbbfe1831a7061b7e0"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9e0106bbb10d08fd05be75dd69664094df05d68"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "a12f7c92dbe4f150cd16b399232bdc2576946709d3879947a417cc4136266fdc"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0c3d36386ce726b2af98ad4039b7c3c62843181"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "85c3d8f0acbd99328446f99aa3b126b6ef8d9dcff0f7eae5551254cfaea3db27"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d13431c771233745b93293d8f15b528e71d57e1"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "a699f9bf3ce827162db3c362d49166687e8759bad91ee86c48087ed1de96db05"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.i686-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db904c678b242f6cc9ca0e88742570e4f69262bb"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "30e5307dfc1be463f94576c31ee87c79a681d534489c039b32b66a33b5c074e5"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.i686-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f261474116ac2e3c1e203890892bff963f3e93f7"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "dcb88260a4bffe63aebee113965d7b295818e6acb37956e90b1b0ed17cb1b3f7"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.i686-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d970d95ab1e4b8bfd1431c5dfb0c760df9c9124e"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "76cc928f68d03f63526785427a3c12aec0309c7c7077941ba2df55e2b92e65bb"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.i686-w64-mingw32-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90bb384e2f939a88814a254ca863c33f8852740b"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "9b2125c8556e264b926e9e8a181878bb7561d5cee9dd4bcca572cd35553af8a9"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8182d7985ef50b6b197eba20ed746b582034355"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "d22da41c68ec753035d97a6e6a4d7605f4ceed7f3c2c21c6003c3496a87fd3ed"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "376e92179219c142c15bc3c3d2065b9ca4f17957"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "d65c97e6b1597e948d28cf55712737db6f22be7521952e9a2d61e76831a09c60"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.x86_64-apple-darwin.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57d99234d7cb6d1ed9dad92c000e58841962ab52"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "e58aa280bc83ca3d16ae2aa3bdb4da80fabde35133c68d0ff5eda0115e7eeb03"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.x86_64-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e257df868dc84440a0c45738a2f68506007fdfbc"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "39a9a6457291c02c999286e7e675a16bbc1b8cd73100aca5f684b40ee841e6b4"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.x86_64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b67d73618c17c61902f970d3f0cdf7995fdd1d0"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "f2f393527050af267d8c761fa0a0084c36211a28aefd5a01a1629bbe98072a44"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.x86_64-linux-musl-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59ef84560598c1aee804bec9b9cede6764ad9211"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "d38d082fb51292ea5a61a0619bf278a46f9268849b970ea23466103146bcad97"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.x86_64-linux-musl-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "a9b249e66b2dcf85e5202ab697d512b6bf4bbc6b"
os = "freebsd"

    [[libcxxwrap_julia.download]]
    sha256 = "e0c90e9b0b47637af42868b1e9212a2c51149500ac1ab83c53866ad618b3ccbb"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.x86_64-unknown-freebsd.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b78dd8d907b8bd17313b74c512f23372e0ea779"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "3ca35f5967a9d4cb01a3c654b5cabfbfc724ebc0cd2213138b7810cee83dd529"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c3bdcefe2a91631853ca7f0e51f9a40008aa8cc"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "3f9dcb50ae65a6f4c363db6d040153beead42942b66c0a4783a811c6e4993242"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.7+0/libcxxwrap_julia.v0.8.7.x86_64-w64-mingw32-cxx11.tar.gz"
