[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "cf64d90f8a541c5137989ba7683d790577eb9ed9"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "eb5f243b7c14d414e3006bc422f807e3bf123dcf1dde6b4ee651ed78e3441e52"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-apple-darwin14.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "28b4ce356821e6194208d70cf89c2b476885ceb6"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "3401dce9796268d9547ab462912c04738ea0f704442a9a6a725d770567d98b03"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-linux-gnu.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
git-tree-sha1 = "31042b78cbbe349cc0a77fe8bcdf23a22cbd2996"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "dcebc074e2cc919abcf8c422fa8c5650757cbf2c8546ae438e897829eb6d2275"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.i686-w64-mingw32.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "20918f084590d6d6c70a7c0589c82bbcf0bd93a1"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "3f8e95bc858eed91ad14aba76494b723d68620dbb775c90c7b11d50d6b17e516"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-w64-mingw32.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0db19ac6f7ae0d651bf10de884d2ce495b8b71b8"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "0d71a02c6181a8685f3d077c47b9b177e8ed71b8609a962a34693695c332c763"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e386cf1aa299baefb56201a2bf3a56b78d54c200"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "f71cd7e85bc04428427072405f679b4857bc266238671d79e7f283a9b3589860"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.i686-w64-mingw32-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b53d12b78cbff6f9fc9049201a4bc23660942c6"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "7cae4324344a41a90a55a7919c2fbddeafeb9c890d04027908b85f5ac5e184e2"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c57d81ea66169fcf8faec4dad83e514f3b4f430d"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "829d0a14417beb1ad364cc61de21de9acf3a95d02769c78caf5c13af5b25cd51"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1839e0ddc0848944f36eb160c77138e7e048cfc1"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "263abf0941c9b22e28cdf55dbfb5b1865064da5e9173d92593956a5bc5822077"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-apple-darwin14-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a90e2f81c3997d8b13a3512b5b385922609393ea"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "b5bb8f7d44c7bcccf9cc8d82e3087a13ff7303651bb9be4c554b1866e2c9d075"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.i686-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9df21bb6fd47cc754e177b5dfb7ce1d6fbd1d4a"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "c61f21f64d82d42e91c978eb9037b90d56e540de24bc87eb4a73b7ef197922c5"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fe12727a7611fbe8289e9e57f227e4c80983ae1"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "d37d1305c67f8aff8ce66f57d8ddda146752bbaa7cf36f012513a0208ae1156b"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-w64-mingw32-cxx11.tar.gz"
