[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c4b61f6589843d59b2f3f43bc4637fb393da90f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "ae892ba6cbe75fa69fb3a05eecd366665d038bc46ee8977a5e109c5c6759881f"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+0/libcxxwrap_julia.v0.7.1.aarch64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b50256b40afc4ff1cc775939a5e1aea3207c8041"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "cf5194ceb4a474d276903080718d1fe8e785ea5f9bb2349c27ff8d6116684b8c"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+0/libcxxwrap_julia.v0.7.1.armv7l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efbc0af8936d1650504fb6674fdc65d3bbec76ba"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "4ede2f96ecf04b9a33831136fbe9580dcd0945678a40948b28edeb4574a251ab"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+0/libcxxwrap_julia.v0.7.1.i686-linux-gnu-libgfortran4-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49d41801aa44f688851bb6a9617f543dea73d823"
libgfortran_version = "4.0.0"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "480d716f782341ee810da935bff74c77bb7d653620921fa579fdad7f4162238d"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+0/libcxxwrap_julia.v0.7.1.x86_64-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ee9f634281320d4ccf83623c3330217ecbc8cdc"
libgfortran_version = "4.0.0"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "1c78a97ba3ace6e33c56219008ace7280111e7d0a0472f9148d187d0b997c6b5"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+0/libcxxwrap_julia.v0.7.1.i686-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e833e7ac389d35aec966c090e46df3ae3d83dffa"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[libcxxwrap_julia.download]]
    sha256 = "5f017c8bc3d10ff4e371208d4f0c319e0179c3767aca89c9446d5f6708e12246"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+0/libcxxwrap_julia.v0.7.1.x86_64-unknown-freebsd11.1-libgfortran4-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9eb8baf82d2a424d6268efb061c676627eba2777"
libgfortran_version = "4.0.0"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "d34f288ce82237b9a651fef31be829c27746caa1158c1451150edcc04db30765"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+0/libcxxwrap_julia.v0.7.1.x86_64-apple-darwin14-libgfortran4-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe0cbe951fc4a4dc82dbc028861699c168dab018"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "9e068d3b254a43c0ef1ab9201a63024518be95e49fb93aefcb134bdf50765493"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.1+0/libcxxwrap_julia.v0.7.1.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
