[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "cf64d90f8a541c5137989ba7683d790577eb9ed9"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "eb5f243b7c14d414e3006bc422f807e3bf123dcf1dde6b4ee651ed78e3441e52"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-apple-darwin14.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "28b4ce356821e6194208d70cf89c2b476885ceb6"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "3401dce9796268d9547ab462912c04738ea0f704442a9a6a725d770567d98b03"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-linux-gnu.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
git-tree-sha1 = "31042b78cbbe349cc0a77fe8bcdf23a22cbd2996"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "dcebc074e2cc919abcf8c422fa8c5650757cbf2c8546ae438e897829eb6d2275"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.i686-w64-mingw32.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "20918f084590d6d6c70a7c0589c82bbcf0bd93a1"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "3f8e95bc858eed91ad14aba76494b723d68620dbb775c90c7b11d50d6b17e516"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.5+0/libcxxwrap_julia.v0.6.5.x86_64-w64-mingw32.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29e467d1d663482316727c03168b3de2842e84b3"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "28b10280a52c73c18a82798ba391ec367bf037e4553aed37f493d49a3ece33f4"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.6+0/libcxxwrap_julia.v0.6.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d97423f79aace800b9667352230c0c907734237d"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "cc5503ad6bad6e7dc3e17ab6e95f08a807d3959dcb634fb5e33be99162fa3245"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.6+0/libcxxwrap_julia.v0.6.6.i686-w64-mingw32-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d6202473ddcca22a6d7c6c527d2ccd99884412f"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "bbd1e5fe3fcb9b5c9ee26091b18abe4eb38c0875a96c63a63feef0c09b66cd54"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.6+0/libcxxwrap_julia.v0.6.6.x86_64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac9279b95da89b1699c6a611de0027582b56fa25"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "d62b2065e4c0dcaefc0612d7c00d6d2c1dd96601dc87dd24730df71c06c0fcc2"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.6+0/libcxxwrap_julia.v0.6.6.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad06ec28ccb73f6c88a4b2810a8b6d9c09d2d218"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "8c2227f8c56aaa8cd1e730b2877b7ca9d172311b67741fc96d920140a55bba37"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.6+0/libcxxwrap_julia.v0.6.6.x86_64-apple-darwin14-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6803ae6993384560ca59fe1befc10435c480471c"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "28b96368e0530a7ada7dd9f1444b89378e46ceb7d00a59bc838aec4e18032892"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.6+0/libcxxwrap_julia.v0.6.6.i686-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bdc681ee14c0171692d434c1192d31647a182b77"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "768865066e4d1b46468674d394e90db972f907b876d44e1cb2dd7a47bc7cce25"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.6+0/libcxxwrap_julia.v0.6.6.x86_64-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd572f506d5bce1020509fee6918f42c429296c2"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "c764ba83621a12196e5824414d5205d62b3803674fa8be4107edcaaa10065973"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.6.6+0/libcxxwrap_julia.v0.6.6.x86_64-w64-mingw32-cxx11.tar.gz"
