[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85cdc72486b257a61b48c7731352464b6bfeaa89"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "d2c11dccc6f7ea5a52586a6364d5e0bad63d3d94af06f9856dcd4ae5cb0c60ef"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db5af0e4892437bddb401152a8b889126a1cfdf7"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "596e948ab2621bc25ed65610c6af419fbc45499a7b3f3666814da3bafee88752"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "962a64e43a8fe482b797df993f1036a78ab8dc07"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "1c4fd6e9995dd1489e429fb04d1e17b1e2a5a04f524fcf761cca93583ac6dc04"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.aarch64-linux-musl-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e287e6ab419500e72860600cba2a546b9a9784d8"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "4e4d4a7743342c4a585cf1b34de1f5b09c7a4e43f060db717e0fb17df2397520"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.aarch64-linux-musl-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83f8ed11f4c891d262930e0bd09434e1a3a3fec3"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "e97cb9d32d775926f574aa9813d2ddb91d025c36f751e9d6fc340ae47f6dcbe4"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f77044493ed7dc9106993b6f3976022081e4fad1"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "bbf52825f60f30e4b2178e45f3fb84be547154adb1b57dca1a78ba5b61698e85"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27efc281806d61f249c93a1df43a956f268089b1"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "7c0416422f50028972e7a747d75d08bbd681daa9a465f5fa259b4c40dfbf48ae"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88b98dfdd63c46a86ddb4a5c0c38ce229372b243"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "e8763caf2c93d5a1b62e3efac64f12cea0fe169ea5e22416311f4ece89d8a9ee"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96c19107492cdf9eb6fb97d1b3bbe7a7edf3c129"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "fe84839d1e736c6ed6f6b7ced730d11e60edb0c6ad9bb66e2b5a1c60de834311"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.i686-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d002c40baadb3490d0c3dc1922068ebe273ee86d"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "2301d917efdf0f317e23296ae17557ce3fd202a60b7f215d9aa6de8618f2644d"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.i686-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91ba1720dff72fe62468f5e6c7df9c324d41624a"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "cebbb68c487a0e037a758a90ce1c0b5699c2c7a3c94799e148f057fc3608c2ba"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.i686-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bdf66c8ddf7a0bc785c2cd58109b8415bbf07ef"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "b1b6faa7415a8287c22cb3419b44b53adfd167c8a13d5394cd573251971f1de0"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.i686-w64-mingw32-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "b5390df558fbaaab86f5e64dd78785bf2c63ffe1"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "e0c34dd17eaedc6b08d9aecd0e18cc7b90fa84ee2cb5049a1812eb4475d25a63"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.x86_64-apple-darwin.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b17eb9430abec6237e8a7b963756bf08464a006"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "5c1cfc948661aad3bb81faca4bf705d9e9a24eb6489ba123c71775a7ac899713"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61bc2e9eab4c22eb15cab30023ce55675e6604d0"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "8877898c278f522c90b6ae69bab4fb830a69a780acbccf7a3ed97bc4ebe3d4c4"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "16bcea7c909ad205c19713e3b6b6ae637311cd1f"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "c9fcfa83dd6fbfa0ae90aa5a9024e9ff14ac7cdd2bd3e717af738d95b585cd98"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.x86_64-linux-musl-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "397d6ef9af3825e64ee891ff1eddbe6682640f18"
libc = "musl"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "cf4920c11e300a65a2e868dc7128247227e561eba103c19e19cb3600512c81dc"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.x86_64-linux-musl-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
git-tree-sha1 = "6a6fc29fd74dfe4c6ca521b950347f3b99289923"
os = "freebsd"

    [[libcxxwrap_julia.download]]
    sha256 = "d3b6285f18c005a6a9a40493ddf00b3cb4bd785e3489102f54ccb7502bd0b9a9"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.x86_64-unknown-freebsd.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a418414a1dae67c504e8d62d58e4397cf5b7b76"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "3ca4b944af055837628b4aabe55a8f1b169ca268dc786c3d19b5fe050c849bb0"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87e441146fc5e7ee7c0f1af84fdf7e13bcb2b48d"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "3a7cc45028031aab57622fdea72ef795440901c290e48cc0e4a2377097ab0f38"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.8.3+0/libcxxwrap_julia.v0.8.3.x86_64-w64-mingw32-cxx11.tar.gz"
