[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f598f80bcf73532d9dd4a75d657d00235079a949"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "05aa4e84a6d263ee2ace408422fca61b5d51830f97a8a7d590aebfe275987351"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.0+0/libcxxwrap_julia.v0.7.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ee5f7398dafd2fced46afea47f1859cf73c370f"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "d3dae775a5821c10669d72c391031c7b46c3c591a59292bde99e26738217b958"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.0+0/libcxxwrap_julia.v0.7.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "295837b46e20ba0ef82ada91b5386bcfdc558004"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "7a26a0894e8af97acf45997d493df101b21dfe65a38359261a6df009e59aba1a"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.0+0/libcxxwrap_julia.v0.7.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a16700620d296e1c452e21a1547541916b1dff6"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "4b2f1d8e3b1383293d5695dd6362488f7d7b188fa8d54611ebdf7bc7f91339be"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.0+0/libcxxwrap_julia.v0.7.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfcd336b2384fd88cd011a33b1aef41fbe215ad3"
os = "windows"

    [[libcxxwrap_julia.download]]
    sha256 = "43dbc83554d0f222292d40b48023e2da2f2d37b86ff5539bef0e5472d5f08b6c"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.0+0/libcxxwrap_julia.v0.7.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcxxwrap_julia]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28d9d19bdb23696f2bf256718b091e9c176ac029"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "18f4e0a6c5b0869984d49f0d6c5ed521dcb18503cbf53ddc8f7dd769c035fcf1"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.0+0/libcxxwrap_julia.v0.7.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b55cd96f4dd60da926644fc18aef04c69f891b7d"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "ed42d74f03d8d00e20427833c7d433906be3957d8e1d0dae8667488181535551"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.0+0/libcxxwrap_julia.v0.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libcxxwrap_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c53c87aa2671a4384df3e5d69637bf97a070202"
libc = "glibc"
os = "linux"

    [[libcxxwrap_julia.download]]
    sha256 = "6aeed9c34c24fe30525f7fc3c2847cdbdf7660ca1f61eda20f1c5dcf9ca80907"
    url = "https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.7.0+0/libcxxwrap_julia.v0.7.0.x86_64-linux-gnu-cxx03.tar.gz"
